/**
 * Manifest Service – business logic for retrieving and creating manifests.
 */
import { StatusCodes } from "http-status-codes";
import { SPVModel } from "../models/spv.model";
import ManifestModel, { IManifest } from "../models/Manifest.model";
import { AppError } from "../errors/AppError";
import type {
  IManifestEntry,
  ListManifestsQuery,
  ManifestListResult,
} from "../types/manifest.types";

const EXCLUDED_FIELDS = { encryptedPayload: 0 } as const;

class ManifestService {
  /**
   * Returns a paginated list of manifests owned by the given Stellar public key.
   * @throws {AppError} 400 – if `limit` or `skip` values are out of range.
   */
  public async listManifests(query: ListManifestsQuery): Promise<ManifestListResult> {
    const { ownerPublicKey, limit, skip } = query;

    if (limit < 1 || limit > 100) {
      throw new AppError(
        "limit must be between 1 and 100",
        StatusCodes.BAD_REQUEST,
        "INVALID_PAGINATION"
      );
    }

    if (skip < 0) {
      throw new AppError(
        "skip must be a non-negative integer",
        StatusCodes.BAD_REQUEST,
        "INVALID_PAGINATION"
      );
    }

    const filter = { ownerPublicKey };

    const [manifests, total] = await Promise.all([
      SPVModel.find(filter, EXCLUDED_FIELDS)
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(limit)
        .lean<IManifestEntry[]>(),
      SPVModel.countDocuments(filter),
    ]);

    return { manifests, total, limit, skip };
  }

  /**
   * Creates and saves a new manifest to the database.
   * The deterministic hash is automatically generated by the pre-save hook in the Model.
   */
  public async createManifest(data: Partial<IManifest>): Promise<IManifest> {
    const newManifest = new ManifestModel(data);
    return await newManifest.save();
  }
}

export const manifestService = new ManifestService();